name: "Docker Build & Push Action"
description: "Reusable Docker build and push steps"

inputs:
  image_name:
    description: "Docker image name"
    required: true
  registry_name:
    description: "ACR registry name"
    required: true
  version:
    description: "Image version"
    required: true
  working-directory:
    description: "Working directory for the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:

    # Cache pip dependencies using actions/cache
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Build Docker image with multi-stage and cache optimization
      run: |
        echo "Building Docker image: ${{ inputs.image_name }}"
        docker build \
          --target final \
          --cache-from ${{ inputs.registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.version }} \
          --tag ${{ inputs.registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.version }} \
          .
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Push Docker image to ACR
      run: |
        docker push ${{ inputs.registry_name }}.azurecr.io/${{ inputs.image_name }}:${{ inputs.version }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
